// SETTINGS
// ======================================================================================================
#define MARGWA_ELEMENTAL_CHECK_IN_ARC														60
#define MARGWA_ELEMENTAL_TYPE_CF																	"margwa_elemental_type"
#define MARGWA_ELEMENTAL_DEFENSE_ACTOR_APPEAR_DISAPPEAR_FX_CF			"margwa_defense_actor_appear_disappear_fx"
#define MARGWA_ELEMENTAL_PLAY_MARGWA_FIRE_ATTACK_CF								"play_margwa_fire_attack_fx"
#define MARGWA_ELEMENTAL_MARGWA_DEFENSE_HOVERING_FX_CF						"margwa_defense_hovering_fx"
#define MARGWA_ELEMENTAL_SHADOW_MARGWA_ATTACK_PORTAL_FX_CF				"shadow_margwa_attack_portal_fx"
#define MARGWA_ELEMENTAL_MARGWA_SHOCK_FX_CF											"margwa_shock_fx"

#define MARGWA_ELEMENTAL_MODEL_HEAD_LEFT													"c_zom_dlc4_margwa_chunks_le"
#define MARGWA_ELEMENTAL_MODEL_HEAD_MID													"c_zom_dlc4_margwa_chunks_mid"
#define MARGWA_ELEMENTAL_MODEL_HEAD_RIGHT												"c_zom_dlc4_margwa_chunks_ri"
#define MARGWA_ELEMENTAL_MODEL_GORE_LEFT													"c_zom_dlc4_margwa_gore_le"
#define MARGWA_ELEMENTAL_MODEL_GORE_MID													"c_zom_dlc4_margwa_gore_mid"
#define MARGWA_ELEMENTAL_MODEL_GORE_RIGHT												"c_zom_dlc4_margwa_gore_ri"
#define MARGWA_ELEMENTAL_LIFT_SCENE																"cin_zm_dlc4_margwa_dth_deathray_01"
#define MARGWA_ELEMENTAL_GRAVITY_TRAP_SCENE												"cin_zm_dlc4_margwa_dth_deathray_02"
#define MARGWA_ELEMENTAL_REACT_STUN_COOLDOWN										10000
#define MARGWA_ELEMENTAL_REACT_IDGUN_COOLDOWN										10000

#define MARGWA_ELEMENTAL_FIRE_MODEL_HEAD_LEFT											"c_zom_dlc4_margwa_chunks_le_fire"
#define MARGWA_ELEMENTAL_FIRE_MODEL_HEAD_MID											"c_zom_dlc4_margwa_chunks_mid_fire"
#define MARGWA_ELEMENTAL_FIRE_MODEL_HEAD_RIGHT										"c_zom_dlc4_margwa_chunks_ri_fire"
#define MARGWA_ELEMENTAL_FIRE_MODEL_GORE_LEFT											"c_zom_dlc4_margwa_gore_le_fire"
#define MARGWA_ELEMENTAL_FIRE_MODEL_GORE_MID											"c_zom_dlc4_margwa_gore_mid_fire"
#define MARGWA_ELEMENTAL_FIRE_MODEL_GORE_RIGHT										"c_zom_dlc4_margwa_gore_ri_fire"
#define MARGWA_ELEMENTAL_FIRE_ROAR_FX															"margwa_fire_roar"
#define MARGWA_ELEMENTAL_FIRE_ROAR_FX_FILE													"dlc4/genesis/fx_margwa_roar_fire"
#define MARGWA_ELEMENTAL_FIRE_SPAWN_FX														"margwa_fire_spawn"
#define MARGWA_ELEMENTAL_FIRE_SPAWN_FX_FILE												"dlc4/genesis/fx_margwa_spawn_fire"
#define MARGWA_ELEMENTAL_FIRE_ATTACK_FX														"margwa_fire_attack_explosion"
#define MARGWA_ELEMENTAL_FIRE_ATTACK_FX_FILE												"dlc4/genesis/fx_margwa_attack_fire"
#define MARGWA_ELEMENTAL_FIRE_DEFENSE_DISAPPEAR_FX									"margwa_fire_defense_disappear"
#define MARGWA_ELEMENTAL_FIRE_DEFENSE_DISAPPEAR_FX_FILE							"dlc4/genesis/fx_margwa_attack_fire"
#define MARGWA_ELEMENTAL_FIRE_DEFENSE_APPEAR_FX										"margwa_fire_defense_appear"
#define MARGWA_ELEMENTAL_FIRE_DEFENSE_APPEAR_FX_FILE								"dlc4/genesis/fx_margwa_attack_fire"
#define MARGWA_ELEMENTAL_FIRE_DEFENSE_FIREBALL_FX										"margwa_fire_defense_fireball"
#define MARGWA_ELEMENTAL_FIRE_DEFENSE_FIREBALL_FX_FILE								"zombie/fx_meatball_portal_sky_zod_zmb"
#define MARGWA_ELEMENTAL_FIRE_HEAD_HIT_FX													"margwa_fire_head_hit"
#define MARGWA_ELEMENTAL_FIRE_HEAD_HIT_FX_FILE											"dlc4/genesis/fx_margwa_head_shot_fire"
#define MARGWA_ELEMENTAL_FIRE_TARGETNAME													"margwa_fire"
#define MARGWA_ELEMENTAL_FIRE_ATTACK_SETUP_COOLDOWN								20000
#define MARGWA_ELEMENTAL_FIRE_ATTACK_MIN_DISTANCE									62500
#define MARGWA_ELEMENTAL_FIRE_ATTACK_MAX_DISTANCE									1440000
#define MARGWA_ELEMENTAL_FIRE_ATTACK_NUM_LOOPS										13.33333
#define MARGWA_ELEMENTAL_FIRE_ATTACK_FAIL_DISTANCE									2304
#define MARGWA_ELEMENTAL_FIRE_DEFEND_SETUP_COOLDOWN								20000
#define MARGWA_ELEMENTAL_FIRE_LIFT_SCENE														"cin_zm_dlc4_margwa_fire_dth_deathray_01"
#define MARGWA_ELEMENTAL_FIRE_GRAVITY_TRAP_SCENE										"cin_zm_dlc4_margwa_fire_dth_deathray_02"

#define MARGWA_ELEMENTAL_SHADOW_MODEL_HEAD_LEFT									"c_zom_dlc4_margwa_chunks_le_shadow"
#define MARGWA_ELEMENTAL_SHADOW_MODEL_HEAD_MID										"c_zom_dlc4_margwa_chunks_mid_shadow"
#define MARGWA_ELEMENTAL_SHADOW_MODEL_HEAD_RIGHT									"c_zom_dlc4_margwa_chunks_ri_shadow"
#define MARGWA_ELEMENTAL_SHADOW_MODEL_GORE_LEFT									"c_zom_dlc4_margwa_gore_le_shadow"
#define MARGWA_ELEMENTAL_SHADOW_MODEL_GORE_MID									"c_zom_dlc4_margwa_gore_mid_shadow"
#define MARGWA_ELEMENTAL_SHADOW_MODEL_GORE_RIGHT									"c_zom_dlc4_margwa_gore_ri_shadow"
#define MARGWA_ELEMENTAL_SHADOW_ROAR_FX													"margwa_shadow_roar"
#define MARGWA_ELEMENTAL_SHADOW_ROAR_FX_FILE											"dlc4/genesis/fx_margwa_roar_shadow"
#define MARGWA_ELEMENTAL_SHADOW_SPAWN_FX												"margwa_shadow_spawn"
#define MARGWA_ELEMENTAL_SHADOW_SPAWN_FX_FILE										"dlc4/genesis/fx_margwa_spawn_shadow"
#define MARGWA_ELEMENTAL_SHADOW_ATTACK_PORTAL_OPEN_FX						"margwa_shadow_attack_portal_open"
#define MARGWA_ELEMENTAL_SHADOW_ATTACK_PORTAL_OPEN_FX_FILE					"dlc4/genesis/fx_margwa_portal_open_shadow"
#define MARGWA_ELEMENTAL_SHADOW_ATTACK_PORTAL_LOOP_FX						"margwa_shadow_attack_portal_loop"
#define MARGWA_ELEMENTAL_SHADOW_ATTACK_PORTAL_LOOP_FX_FILE					"dlc4/genesis/fx_margwa_portal_loop_shadow"
#define MARGWA_ELEMENTAL_SHADOW_ATTACK_PORTAL_CLOSE_FX						"margwa_shadow_attack_portal_close"
#define MARGWA_ELEMENTAL_SHADOW_ATTACK_PORTAL_CLOSE_FX_FILE				"dlc4/genesis/fx_margwa_portal_close_shadow"
#define MARGWA_ELEMENTAL_SHADOW_DEFENSE_DISAPPEAR_FX							"margwa_shadow_defense_disappear"
#define MARGWA_ELEMENTAL_SHADOW_DEFENSE_DISAPPEAR_FX_FILE					"dlc1/castle/fx_demon_gate_portal_open"
#define MARGWA_ELEMENTAL_SHADOW_DEFENSE_APPEAR_FX									"margwa_shadow_defense_appear"
#define MARGWA_ELEMENTAL_SHADOW_DEFENSE_APPEAR_FX_FILE							"dlc1/castle/fx_demon_gate_portal_open"
#define MARGWA_ELEMENTAL_SHADOW_DEFENSE_BALL_FX										"margwa_shadow_defense_ball"
#define MARGWA_ELEMENTAL_SHADOW_DEFENSE_BALL_FX_FILE								"smoke/fx_smk_barrel_30x30"
#define MARGWA_ELEMENTAL_SHADOW_HEAD_HIT_FX											"margwa_shadow_head_hit"
#define MARGWA_ELEMENTAL_SHADOW_HEAD_HIT_FX_FILE									"dlc4/genesis/fx_margwa_head_shot_shadow"
#define MARGWA_ELEMENTAL_SHADOW_TARGETNAME											"margwa_shadow"
#define MARGWA_ELEMENTAL_SHADOW_ATTACK_WEAPON										"launcher_shadow_margwa"
#define MARGWA_ELEMENTAL_SHADOW_ATTACK_SETUP_COOLDOWN						20000
#define MARGWA_ELEMENTAL_SHADOW_ATTACK_COOLDOWN									100000
#define MARGWA_ELEMENTAL_SHADOW_ATTACK_LENGTH										1000
#define MARGWA_ELEMENTAL_SHADOW_ATTACK_MIN_DISTANCE							16384
#define MARGWA_ELEMENTAL_SHADOW_ATTACK_MAX_DISTANCE							589824
#define MARGWA_ELEMENTAL_SHADOW_DEFEND_SETUP_COOLDOWN						20000
#define MARGWA_ELEMENTAL_SHADOW_LIFT_SCENE												"cin_zm_dlc4_margwa_shadow_dth_deathray_01"
#define MARGWA_ELEMENTAL_SHADOW_GRAVITY_TRAP_SCENE								"cin_zm_dlc4_margwa_shadow_dth_deathray_02"
#define MARGWA_ELEMENTAL_SHADOW_ATTACK_CHOMP_ANIM								"ai_zm_dlc4_chomper_shadow_margwa_projectile"
#define MARGWA_ELEMENTAL_SHADOW_PORTAL_OPEN_SOUND								"zmb_margwa_shadow_portal_open"
#define MARGWA_ELEMENTAL_SHADOW_PORTAL_LOOP_SOUND								"zmb_margwa_shadow_portal_lp"
#define MARGWA_ELEMENTAL_SHADOW_PORTAL_CLOSE_SOUND								"zmb_margwa_shadow_portal_close"

#define MARGWA_ELEMENTAL_LIGHT_ROAR_FX														"margwa_light_roar"
#define MARGWA_ELEMENTAL_LIGHT_ROAR_FX_FILE												"dlc4/genesis/fx_margwa_roar_light"
#define MARGWA_ELEMENTAL_LIGHT_SPAWN_FX														"margwa_light_spawn"
#define MARGWA_ELEMENTAL_LIGHT_SPAWN_FX_FILE												"dlc4/genesis/fx_margwa_spawn"
#define MARGWA_ELEMENTAL_LIGHT_TARGETNAME													"margwa_light"
#define MARGWA_ELEMENTAL_LIGHT_ATTACK_SETUP_COOLDOWN							3000
#define MARGWA_ELEMENTAL_LIGHT_ATTACK_MIN_DISTANCE								62500
#define MARGWA_ELEMENTAL_LIGHT_ATTACK_MAX_DISTANCE								1440000
#define MARGWA_ELEMENTAL_LIGHT_DEFEND_SETUP_COOLDOWN							20000

#define MARGWA_ELEMENTAL_ELECTRIC_ROAR_FX													"margwa_electric_roar"
#define MARGWA_ELEMENTAL_ELECTRIC_ROAR_FX_FILE											"dlc4/genesis/fx_margwa_roar_electricity"
#define MARGWA_ELEMENTAL_ELECTRIC_SPAWN_FX												"margwa_electric_spawn"
#define MARGWA_ELEMENTAL_ELECTRIC_SPAWN_FX_FILE										"dlc4/genesis/fx_margwa_spawn"
#define MARGWA_ELEMENTAL_ELECTRIC_TARGETNAME											"margwa_electric"
#define MARGWA_ELEMENTAL_ELECTRIC_ATTACK_SETUP_COOLDOWN						6000
#define MARGWA_ELEMENTAL_ELECTRIC_ATTACK_MIN_DISTANCE							62500
#define MARGWA_ELEMENTAL_ELECTRIC_ATTACK_MAX_DISTANCE							1440000
#define MARGWA_ELEMENTAL_ELECTRIC_SHOOT_ATTACK_MIN_DISTANCE				62500
#define MARGWA_ELEMENTAL_ELECTRIC_SHOOT_ATTACK_MAX_DISTANCE				1440000
#define MARGWA_ELEMENTAL_ELECTRIC_DEFEND_MIN_DISTANCE							129600
#define MARGWA_ELEMENTAL_ELECTRIC_DEFEND_MAX_DISTANCE							921600
#define MARGWA_ELEMENTAL_ELECTRIC_SHOOT_ATTACK_SETUP_COOLDOWN			6000
#define MARGWA_ELEMENTAL_ELECTRIC_DEFEND_SETUP_COOLDOWN						7500