// SETTINGS
// ======================================================================================================
#define	NAPALM_ZOMBIE_MINIMUM_ROUND_WAIT							1					
#define	NAPALM_ZOMBIE_MAXIMUM_ROUND_WAIT							2			
#define	NAPALM_ZOMBIE_ROUND_REQUIREMENT							5				
#define	NAPALM_ZOMBIE_EXPLODE_DAMAGE_MIN							50
#define	NAPALM_ZOMBIE_EXPLODE_DAMAGE_RADIUS						400
#define	NAPALM_ZOMBIE_EXPLODE_DAMAGE_RADIUS_WET				250
#define	NAPALM_ZOMBIE_DAMAGE_RADIUS									250
#define	NAPALM_ZOMBIE_EXPLODE_RADIUS									90
#define	NAPALM_ZOMBIE_WARNING_RADIUS_TIME							10000
#define	NAPALM_ZOMBIE_KILL_RADIUS											150
#define	NAPALM_ZOMBIE_KILL_RADIUS_JUGG								90
#define	NAPALM_ZOMBIE_TIME_BEFORE_EXPLODE_POSSIBLE			2000
#define	NAPALM_ZOMBIE_HEALTH_MULTIPLIER								4
